spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  #thymeleaf
  thymeleaf:
    cache: false
  #druid
  datasource:
    url: jdbc:mysql://116.62.48.112:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #rabbitmq
  rabbitmq:
    host: 116.62.48.112
    port: 5672
    username: guest
    password: guest
    #连接到rabbitMQ的vhost
    virtual-host: /
    listener:
      simple:
        #消费者数量
        concurrency: 10
        max-concurrency: 10
        #指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量.
        prefetch: 1
        #是否启动时自动启动容器
        auto-startup: true
        #决定被拒绝的消息是否重新入队；默认是true（与参数acknowledge-mode有关系）
        default-requeue-rejected: true
    template:
      retry:
        #发送重试是否可用
        enabled: true
        #第一次和第二次尝试发布或传递消息之间的间隔
        initial-interval: 1000
        #最大重试次数
        max-attempts: 3
        #最大重试时间间隔
        max-interval: 10000
        #应用于上一重试间隔的乘数
        multiplier: 1.0

#mybatis
mybatis:
  #数据彪对应的实体类
  type-aliases-package: com.soldier.domain
  configuration:
    #驼峰命名法
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  #接口配置文件
  mapper-locations: classpath:mapper/*.xml
#redis
redis:
  host: 116.62.48.112
  port: 6379
  #超时时间
  timeout: 10
  password: 123456
  #连接池最大连接个数
  poolMaxTotal: 1000
  #连接池最大空闲
  poolMaxIdle: 500
  #连接池最大等待
  poolMaxWait: 500